In [48]:
import numpy as np
a = np.arange(1,9)
b = np.arange(2,10)
c = np.arange(0,8)
print(a)
print(b)
print(c)
vector = np.empty((1,))

[1 2 3 4 5 6 7 8]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]


In [49]:
def add_state(vector, a):
    if vector == np.empty((1,)):
        vector = a
    else:
        if vector.shape[0]==1:
            vector = np.concatenate((vector,a)).reshape((2,a.shape[0]))
        else:
            vector = np.concatenate((vector,a))
    return vector

In [50]:
vector = add_state(vector, a)
print(vector)

ValueError: cannot reshape array of size 9 into shape (2,8)

In [38]:
vector = add_state(vector, b)
print(vector)

[1. 2. 3. 4. 5. 6. 7. 8. 2. 3. 4. 5. 6. 7. 8. 9.]


C:\Users\acer\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


In [39]:
vector = add_state(vector, c)
print(vector)

[1. 2. 3. 4. 5. 6. 7. 8. 2. 3. 4. 5. 6. 7. 8. 9. 0. 1. 2. 3. 4. 5. 6. 7.]


C:\Users\acer\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  
