In [18]:
import numpy as np

In [19]:
a = np.arange(6).reshape((3,2))
print(a)
c = []

[[0 1]
 [2 3]
 [4 5]]


In [20]:
b = np.array([7,8,9]).reshape((3,1))
print(a.shape)
print(b.shape)
c = np.concatenate((a,b),axis=1)
print(c)

(3, 2)
(3, 1)
[[0 1 7]
 [2 3 8]
 [4 5 9]]
